/*export const supabaseUrl = "https://hsolfvbckjymikzifhxa.supabase.co";
export const supabaseAnonKey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhzb2xmdmJja2p5bWlremlmaHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY1MDYwNDAsImV4cCI6MjA0MjA4MjA0MH0.giflkKyJ0P83jrRQEhDuxoqoXjprTgu6hc-ZjJuJcEU";
*/
//EXPO_PUBLIC_SUPABASE_URL=https://hsolfvbckjymikzifhxa.supabase.co
//EXPO_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhzb2xmdmJja2p5bWlremlmaHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY1MDYwNDAsImV4cCI6MjA0MjA4MjA0MH0.giflkKyJ0P83jrRQEhDuxoqoXjprTgu6hc-ZjJuJcEU

export const supabaseUrl = "https://vkcwdlwmyjxvzzacidnn.supabase.co";
export const supabaseAnonKey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrY3dkbHdteWp4dnp6YWNpZG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMzI0NDQsImV4cCI6MjA0OTYwODQ0NH0.g39TMGZL5Y1aD6FBGX_mS9oNBqhSjKMUkdmB8fsduWA";
